
spring:
  # 环境 dev|prod|docker
  profiles:
    active: dev
  #文件上传设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER



  # #activeMQ配置 ( 注意： activeMQ配置项需在spring的下级 )
  activemq:
    broker-url: failover:(tcp://127.0.0.1:61616?wireFormat.maxInactivityDuration=0)  #连接地址
    in-memory: false # Jeepay项目不可使用内存模式， 需要连接多个消费者。
    user: system # activeMQ默认无需账密认证。 打开认证：activemq.xml添加simpleAuthenticationPlugin标签，账密在credentials.properties文件。
    password: manager
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000  # 空闲的连接过期时间，默认为30秒

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      select-strategy: NOT_NULL
      # 默认数据库表下划线命名
      table-underline: true

management:
  server:
    add-application-context-header: false
server:
  tomcat:
    basedir: /temp
# 用于雪花算法生成id
application:
  datacenterId: ${DATACENTER_ID:1}
  workerId: ${WORKER_ID:1}

mall4j:
  order:
    thread:
      coreSize: 0
      maxSize: 200
      keepAliveTime: 60

isys:
  mq:
    vender: activeMQ
